// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQOfzabTz96i4h0lS-JipBdt44C_sO-o',
    appId: '1:637913467588:web:c7cc725326b6cc33f35791',
    messagingSenderId: '637913467588',
    projectId: 'disciplineportal',
    authDomain: 'disciplineportal.firebaseapp.com',
    storageBucket: 'disciplineportal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiofcWsE2unU_Iw59lYT9K82y2nQ9huz8',
    appId: '1:637913467588:android:ef26e500039881b4f35791',
    messagingSenderId: '637913467588',
    projectId: 'disciplineportal',
    storageBucket: 'disciplineportal.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFQOfzabTz96i4h0lS-JipBdt44C_sO-o',
    appId: '1:637913467588:web:8bb954bd225f7ef1f35791',
    messagingSenderId: '637913467588',
    projectId: 'disciplineportal',
    authDomain: 'disciplineportal.firebaseapp.com',
    storageBucket: 'disciplineportal.firebasestorage.app',
  );

}